-- Добавление тестовых операций в таблицу operations
INSERT INTO operations (
    id,
    operation_type,
    status,
    start_time,
    end_time,
    duration,
    trading_point_id,
    trading_point_name,
    device_id,
    transaction_id,
    fuel_type,
    quantity,
    price,
    total_cost,
    payment_method,
    details,
    progress,
    operator_name,
    customer_id,
    vehicle_number,
    metadata
) VALUES 
(
    'op-001',
    'sale',
    'completed',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour 55 minutes',
    300,
    'tp-001',
    'АЗС Центральная',
    'pump-01',
    'txn-001',
    'АИ-95',
    35.50,
    52.30,
    1856.65,
    'bank_card',
    'Обычная продажа топлива',
    100,
    'Иванов А.П.',
    'cust-001',
    'А123БВ77',
    '{"receipt_number": "12345", "bonus_points": 18}'::jsonb
),
(
    'op-002',
    'sale',
    'completed',
    NOW() - INTERVAL '1 hour 30 minutes',
    NOW() - INTERVAL '1 hour 25 minutes',
    300,
    'tp-001',
    'АЗС Центральная',
    'pump-02',
    'txn-002',
    'ДТ',
    50.00,
    54.80,
    2740.00,
    'cash',
    'Продажа дизельного топлива',
    100,
    'Петров С.И.',
    'cust-002',
    'В456ГД99',
    '{"receipt_number": "12346"}'::jsonb
),
(
    'op-003',
    'sale',
    'in_progress',
    NOW() - INTERVAL '5 minutes',
    NULL,
    NULL,
    'tp-002',
    'АЗС Северная',
    'pump-03',
    'txn-003',
    'АИ-92',
    25.00,
    50.90,
    1272.50,
    'bank_card',
    'Заправка в процессе',
    75,
    'Сидоров В.К.',
    'cust-003',
    'Е789ЖЗ55',
    '{"estimated_time": "2 min"}'::jsonb
),
(
    'op-004',
    'refund',
    'completed',
    NOW() - INTERVAL '3 hours',
    NOW() - INTERVAL '2 hours 55 minutes',
    300,
    'tp-001',
    'АЗС Центральная',
    'pump-01',
    'txn-004',
    'АИ-95',
    15.00,
    52.30,
    784.50,
    'bank_card',
    'Возврат из-за некачественного топлива',
    100,
    'Иванов А.П.',
    'cust-004',
    'И012КЛ33',
    '{"refund_reason": "quality_issue", "original_txn": "txn-001"}'::jsonb
),
(
    'op-005',
    'maintenance',
    'completed',
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '5 hours',
    3600,
    'tp-001',
    'АЗС Центральная',
    'pump-02',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Плановое ТО колонки №2',
    100,
    'Техник Козлов Д.А.',
    NULL,
    NULL,
    '{"maintenance_type": "scheduled", "work_performed": ["filter_change", "calibration"]}'::jsonb
);

-- Проверяем добавленные данные
SELECT COUNT(*) as total_operations FROM operations;
SELECT id, operation_type, status, fuel_type, total_cost, details FROM operations ORDER BY created_at DESC;