-- Добавление тестовых операций в таблицу operations
-- Для демонстрации работы API раздела операций

INSERT INTO operations (
    id,
    operation_type,
    status,
    start_time,
    end_time,
    duration,
    trading_point_id,
    trading_point_name,
    device_id,
    transaction_id,
    fuel_type,
    quantity,
    price,
    total_cost,
    payment_method,
    details,
    progress,
    operator_name,
    customer_id,
    vehicle_number,
    metadata,
    created_at,
    updated_at
) VALUES 
-- Продажи топлива
(
    'op-001',
    'sale',
    'completed',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour 55 minutes',
    300, -- 5 минут в секундах
    'tp-001',
    'АЗС Центральная',
    'pump-01',
    'txn-001',
    'АИ-95',
    35.50,
    52.30,
    1856.65,
    'bank_card',
    'Обычная продажа топлива',
    100,
    'Иванов А.П.',
    'cust-001',
    'А123БВ77',
    '{"receipt_number": "12345", "bonus_points": 18}',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour 55 minutes'
),
(
    'op-002',
    'sale',
    'completed',
    NOW() - INTERVAL '1 hour 30 minutes',
    NOW() - INTERVAL '1 hour 25 minutes',
    300,
    'tp-001',
    'АЗС Центральная',
    'pump-02',
    'txn-002',
    'ДТ',
    50.00,
    54.80,
    2740.00,
    'cash',
    'Продажа дизельного топлива',
    100,
    'Петров С.И.',
    'cust-002',
    'В456ГД99',
    '{"receipt_number": "12346"}',
    NOW() - INTERVAL '1 hour 30 minutes',
    NOW() - INTERVAL '1 hour 25 minutes'
),
(
    'op-003',
    'sale',
    'in_progress',
    NOW() - INTERVAL '5 minutes',
    NULL,
    NULL,
    'tp-002',
    'АЗС Северная',
    'pump-03',
    'txn-003',
    'АИ-92',
    25.00,
    50.90,
    1272.50,
    'bank_card',
    'Заправка в процессе',
    75,
    'Сидоров В.К.',
    'cust-003',
    'Е789ЖЗ55',
    '{"estimated_time": "2 min"}',
    NOW() - INTERVAL '5 minutes',
    NOW() - INTERVAL '1 minute'
),

-- Возврат
(
    'op-004',
    'refund',
    'completed',
    NOW() - INTERVAL '3 hours',
    NOW() - INTERVAL '2 hours 55 minutes',
    300,
    'tp-001',
    'АЗС Центральная',
    'pump-01',
    'txn-004',
    'АИ-95',
    15.00,
    52.30,
    784.50,
    'bank_card',
    'Возврат из-за некачественного топлива',
    100,
    'Иванов А.П.',
    'cust-004',
    'И012КЛ33',
    '{"refund_reason": "quality_issue", "original_txn": "txn-001"}',
    NOW() - INTERVAL '3 hours',
    NOW() - INTERVAL '2 hours 55 minutes'
),

-- Техническое обслуживание
(
    'op-005',
    'maintenance',
    'completed',
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '5 hours',
    3600, -- 1 час
    'tp-001',
    'АЗС Центральная',
    'pump-02',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Плановое ТО колонки №2',
    100,
    'Техник Козлов Д.А.',
    NULL,
    NULL,
    '{"maintenance_type": "scheduled", "work_performed": ["filter_change", "calibration"]}',
    NOW() - INTERVAL '6 hours',
    NOW() - INTERVAL '5 hours'
),

-- Загрузка резервуара
(
    'op-006',
    'tank_loading',
    'completed',
    NOW() - INTERVAL '8 hours',
    NOW() - INTERVAL '6 hours',
    7200, -- 2 часа
    'tp-002',
    'АЗС Северная',
    'tank-01',
    'load-001',
    'АИ-95',
    5000.00,
    51.20,
    256000.00,
    'bank_transfer',
    'Загрузка резервуара АИ-95',
    100,
    'Водитель Морозов И.И.',
    NULL,
    'Т678УФ88',
    '{"supplier": "НефтеТрейд", "batch_number": "BT-2024-001", "quality_cert": "QC-001"}',
    NOW() - INTERVAL '8 hours',
    NOW() - INTERVAL '6 hours'
),

-- Диагностика оборудования
(
    'op-007',
    'diagnostics',
    'failed',
    NOW() - INTERVAL '4 hours',
    NOW() - INTERVAL '3 hours 30 minutes',
    1800, -- 30 минут
    'tp-002',
    'АЗС Северная',
    'pump-04',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Диагностика выявила неисправность датчика',
    100,
    'Техник Волков П.Р.',
    NULL,
    NULL,
    '{"error_code": "E-404", "issue": "sensor_malfunction", "requires_replacement": true}',
    NOW() - INTERVAL '4 hours',
    NOW() - INTERVAL '3 hours 30 minutes'
),

-- Калибровка датчиков
(
    'op-008',
    'sensor_calibration',
    'in_progress',
    NOW() - INTERVAL '30 minutes',
    NULL,
    NULL,
    'tp-001',
    'АЗС Центральная',
    'tank-02',
    NULL,
    'ДТ',
    NULL,
    NULL,
    NULL,
    NULL,
    'Калибровка датчика уровня топлива',
    60,
    'Техник Белов А.А.',
    NULL,
    NULL,
    '{"calibration_type": "level_sensor", "expected_duration": "45 min"}',
    NOW() - INTERVAL '30 minutes',
    NOW() - INTERVAL '5 minutes'
),

-- Еще несколько продаж для статистики
(
    'op-009',
    'sale',
    'completed',
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '40 minutes',
    300,
    'tp-001',
    'АЗС Центральная',
    'pump-03',
    'txn-009',
    'АИ-95',
    40.00,
    52.30,
    2092.00,
    'fuel_card',
    'Продажа по топливной карте',
    100,
    'Иванов А.П.',
    'cust-009',
    'Н345ОП11',
    '{"fuel_card": "FC-789456", "discount": 5}',
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '40 minutes'
),
(
    'op-010',
    'sale',
    'completed',
    NOW() - INTERVAL '15 minutes',
    NOW() - INTERVAL '10 minutes',
    300,
    'tp-002',
    'АЗС Северная',
    'pump-05',
    'txn-010',
    'АИ-92',
    30.00,
    50.90,
    1527.00,
    'bank_card',
    'Обычная продажа АИ-92',
    100,
    'Сидоров В.К.',
    'cust-010',
    'Р678СТ22',
    '{"receipt_number": "12350"}',
    NOW() - INTERVAL '15 minutes',
    NOW() - INTERVAL '10 minutes'
);

-- Обновляем счетчики последовательностей если используются
-- SELECT setval('operations_id_seq', (SELECT MAX(id) FROM operations) + 1);