import { Equipment, EquipmentComponent, EquipmentEvent, EquipmentStatusAction, EquipmentTemplate } from '@/types/equipment';
import { mockEquipmentAPI } from './equipment';

// Обновленные резервуары для всех АЗС демо сети
const newEquipmentData: Equipment[] = [
  // АЗС №001 - Центральная (point1) - Полный сервис: АИ-92, АИ-95, ДТ, АИ-98
  {
    id: "tank_p1_92",
    trading_point_id: "point1",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-92 - Резервуар №1",
    serial_number: "TANK-001-92",
    external_id: "TANK_P1_92",
    status: "online",
    installation_date: "2024-01-15T00:00:00Z",
    params: {
      id: 1,
      name: "АИ-92 - Резервуар №1",
      fuelType: "АИ-92",
      currentLevelLiters: 38000,
      capacityLiters: 50000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 50000,
      temperature: 15.2,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-01-15T12:00:00Z",
    updated_at: "2024-12-08T10:30:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p1_95",
    trading_point_id: "point1",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-95 - Резервуар №2",
    serial_number: "TANK-001-95",
    external_id: "TANK_P1_95",
    status: "online",
    installation_date: "2024-01-15T00:00:00Z",
    params: {
      id: 2,
      name: "АИ-95 - Резервуар №2", 
      fuelType: "АИ-95",
      currentLevelLiters: 42000,
      capacityLiters: 50000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 50000,
      temperature: 15.8,
      waterLevelMm: 2,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-01-15T12:00:00Z",
    updated_at: "2024-12-08T09:15:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p1_dt",
    trading_point_id: "point1",
    name: "Резервуар", 
    system_type: "fuel_tank",
    display_name: "ДТ - Резервуар №3",
    serial_number: "TANK-001-DT",
    external_id: "TANK_P1_DT",
    status: "online",
    installation_date: "2024-01-15T00:00:00Z",
    params: {
      id: 3,
      name: "ДТ - Резервуар №3",
      fuelType: "ДТ",
      currentLevelLiters: 28000,
      capacityLiters: 40000,
      minLevelPercent: 25,
      criticalLevelPercent: 12,
      volume: 40000,
      temperature: 16.5,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-01-15T12:00:00Z",
    updated_at: "2024-12-08T11:45:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p1_98",
    trading_point_id: "point1",
    name: "Резервуар",
    system_type: "fuel_tank", 
    display_name: "АИ-98 - Резервуар №4",
    serial_number: "TANK-001-98",
    external_id: "TANK_P1_98",
    status: "online",
    installation_date: "2024-01-15T00:00:00Z",
    params: {
      id: 4,
      name: "АИ-98 - Резервуар №4",
      fuelType: "АИ-98",
      currentLevelLiters: 18500,
      capacityLiters: 25000,
      minLevelPercent: 18,
      criticalLevelPercent: 9,
      volume: 25000,
      temperature: 16.1,
      waterLevelMm: 0.5,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-01-15T12:00:00Z",
    updated_at: "2024-12-08T08:30:00Z", 
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },

  // АЗС №002 - Северная (point2) - Коммерческий транспорт: АИ-92, ДТ, АИ-100
  {
    id: "tank_p2_92",
    trading_point_id: "point2",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-92 - Резервуар №1",
    serial_number: "TANK-002-92",
    external_id: "TANK_P2_92",
    status: "online",
    installation_date: "2024-02-01T00:00:00Z",
    params: {
      id: 5,
      name: "АИ-92 - Резервуар №1",
      fuelType: "АИ-92",
      currentLevelLiters: 35000,
      capacityLiters: 50000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 50000,
      temperature: 14.8,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-02-01T12:00:00Z",
    updated_at: "2024-12-08T09:20:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p2_dt",
    trading_point_id: "point2",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "ДТ - Резервуар №2",
    serial_number: "TANK-002-DT",
    external_id: "TANK_P2_DT",
    status: "online",
    installation_date: "2024-02-01T00:00:00Z",
    params: {
      id: 6,
      name: "ДТ - Резервуар №2",
      fuelType: "ДТ",
      currentLevelLiters: 45000,
      capacityLiters: 60000,
      minLevelPercent: 25,
      criticalLevelPercent: 12,
      volume: 60000,
      temperature: 15.2,
      waterLevelMm: 2,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-02-01T12:00:00Z",
    updated_at: "2024-12-08T10:15:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p2_100",
    trading_point_id: "point2",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-100 - Резервуар №3",
    serial_number: "TANK-002-100",
    external_id: "TANK_P2_100",
    status: "online",
    installation_date: "2024-02-01T00:00:00Z",
    params: {
      id: 7,
      name: "АИ-100 - Резервуар №3",
      fuelType: "АИ-100",
      currentLevelLiters: 12000,
      capacityLiters: 20000,
      minLevelPercent: 15,
      criticalLevelPercent: 8,
      volume: 20000,
      temperature: 15.5,
      waterLevelMm: 0.5,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-02-01T12:00:00Z",
    updated_at: "2024-12-08T11:00:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },

  // АЗС №003 - Южная (point3) - Семейная АЗС: АИ-92, АИ-95
  {
    id: "tank_p3_92",
    trading_point_id: "point3",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-92 - Резервуар №1",
    serial_number: "TANK-003-92",
    external_id: "TANK_P3_92",
    status: "online",
    installation_date: "2024-03-01T00:00:00Z",
    params: {
      id: 8,
      name: "АИ-92 - Резервуар №1",
      fuelType: "АИ-92",
      currentLevelLiters: 30000,
      capacityLiters: 40000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 40000,
      temperature: 16.2,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-03-01T12:00:00Z",
    updated_at: "2024-12-08T09:45:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p3_95",
    trading_point_id: "point3",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-95 - Резервуар №2",
    serial_number: "TANK-003-95",
    external_id: "TANK_P3_95",
    status: "online",
    installation_date: "2024-03-01T00:00:00Z",
    params: {
      id: 9,
      name: "АИ-95 - Резервуар №2",
      fuelType: "АИ-95",
      currentLevelLiters: 32000,
      capacityLiters: 40000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 40000,
      temperature: 15.9,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-03-01T12:00:00Z",
    updated_at: "2024-12-08T10:30:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },

  // АЗС №004 - Московское шоссе (point4) - Трассовая 24/7: АИ-92, АИ-95, ДТ
  {
    id: "tank_p4_92",
    trading_point_id: "point4",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-92 - Резервуар №1",
    serial_number: "TANK-004-92",
    external_id: "TANK_P4_92",
    status: "online",
    installation_date: "2024-04-01T00:00:00Z",
    params: {
      id: 10,
      name: "АИ-92 - Резервуар №1",
      fuelType: "АИ-92",
      currentLevelLiters: 48000,
      capacityLiters: 60000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 60000,
      temperature: 14.5,
      waterLevelMm: 2,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-04-01T12:00:00Z",
    updated_at: "2024-12-08T08:15:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p4_95",
    trading_point_id: "point4",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-95 - Резервуар №2",
    serial_number: "TANK-004-95",
    external_id: "TANK_P4_95",
    status: "online",
    installation_date: "2024-04-01T00:00:00Z",
    params: {
      id: 11,
      name: "АИ-95 - Резервуар №2",
      fuelType: "АИ-95",
      currentLevelLiters: 52000,
      capacityLiters: 60000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 60000,
      temperature: 15.1,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-04-01T12:00:00Z",
    updated_at: "2024-12-08T09:30:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p4_dt",
    trading_point_id: "point4",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "ДТ - Резервуар №3",
    serial_number: "TANK-004-DT",
    external_id: "TANK_P4_DT",
    status: "online",
    installation_date: "2024-04-01T00:00:00Z",
    params: {
      id: 12,
      name: "ДТ - Резервуар №3",
      fuelType: "ДТ",
      currentLevelLiters: 38000,
      capacityLiters: 50000,
      minLevelPercent: 25,
      criticalLevelPercent: 12,
      volume: 50000,
      temperature: 16.8,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-04-01T12:00:00Z",
    updated_at: "2024-12-08T11:20:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },

  // АЗС №005 - Промзона (point5) - Промышленная для коммерческих клиентов: ДТ, АИ-92
  {
    id: "tank_p5_dt",
    trading_point_id: "point5",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "ДТ - Резервуар №1",
    serial_number: "TANK-005-DT",
    external_id: "TANK_P5_DT",
    status: "online",
    installation_date: "2024-05-01T00:00:00Z",
    params: {
      id: 13,
      name: "ДТ - Резервуар №1",
      fuelType: "ДТ",
      currentLevelLiters: 55000,
      capacityLiters: 70000,
      minLevelPercent: 25,
      criticalLevelPercent: 12,
      volume: 70000,
      temperature: 17.2,
      waterLevelMm: 3,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-05-01T12:00:00Z",
    updated_at: "2024-12-08T10:45:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "tank_p5_92",
    trading_point_id: "point5",
    name: "Резервуар",
    system_type: "fuel_tank",
    display_name: "АИ-92 - Резервуар №2",
    serial_number: "TANK-005-92",
    external_id: "TANK_P5_92",
    status: "online",
    installation_date: "2024-05-01T00:00:00Z",
    params: {
      id: 14,
      name: "АИ-92 - Резервуар №2",
      fuelType: "АИ-92",
      currentLevelLiters: 25000,
      capacityLiters: 35000,
      minLevelPercent: 20,
      criticalLevelPercent: 10,
      volume: 35000,
      temperature: 14.9,
      waterLevelMm: 1,
      material: "steel",
      thresholds: { criticalTemp: { min: -10, max: 40 }, maxWaterLevel: 15 }
    },
    created_at: "2024-05-01T12:00:00Z",
    updated_at: "2024-12-08T09:00:00Z",
    created_from_template: "1",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },

  // Системы управления для каждой АЗС
  {
    id: "control_p1",
    trading_point_id: "point1",
    name: "Система управления",
    system_type: "control_system",
    display_name: "Система управления АЗС №001",
    serial_number: "CTRL-001",
    external_id: "CTRL_P1",
    status: "online",
    installation_date: "2024-01-10T00:00:00Z",
    params: { server_type: "industrial", redundancy: true, uptime: 99.98, load: 45, connections: 12 },
    created_at: "2024-01-10T12:00:00Z",
    updated_at: "2024-12-08T11:00:00Z",
    created_from_template: "3",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "control_p2",
    trading_point_id: "point2",
    name: "Система управления",
    system_type: "control_system",
    display_name: "Система управления АЗС №002",
    serial_number: "CTRL-002",
    external_id: "CTRL_P2",
    status: "online",
    installation_date: "2024-02-10T00:00:00Z",
    params: { server_type: "industrial", redundancy: true, uptime: 99.95, load: 38, connections: 8 },
    created_at: "2024-02-10T12:00:00Z",
    updated_at: "2024-12-08T10:45:00Z",
    created_from_template: "3",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "control_p3",
    trading_point_id: "point3",
    name: "Система управления",
    system_type: "control_system",
    display_name: "Система управления АЗС №003",
    serial_number: "CTRL-003",
    external_id: "CTRL_P3",
    status: "online",
    installation_date: "2024-03-10T00:00:00Z",
    params: { server_type: "industrial", redundancy: false, uptime: 99.92, load: 22, connections: 4 },
    created_at: "2024-03-10T12:00:00Z",
    updated_at: "2024-12-08T09:30:00Z",
    created_from_template: "3",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "control_p4",
    trading_point_id: "point4",
    name: "Система управления",
    system_type: "control_system",
    display_name: "Система управления АЗС №004",
    serial_number: "CTRL-004",
    external_id: "CTRL_P4",
    status: "online",
    installation_date: "2024-04-10T00:00:00Z",
    params: { server_type: "industrial", redundancy: true, uptime: 99.99, load: 52, connections: 16 },
    created_at: "2024-04-10T12:00:00Z",
    updated_at: "2024-12-08T11:15:00Z",
    created_from_template: "3",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  },
  {
    id: "control_p5",
    trading_point_id: "point5",
    name: "Система управления",
    system_type: "control_system",
    display_name: "Система управления АЗС №005",
    serial_number: "CTRL-005",
    external_id: "CTRL_P5",
    status: "online",
    installation_date: "2024-05-10T00:00:00Z",
    params: { server_type: "industrial", redundancy: true, uptime: 99.96, load: 41, connections: 10 },
    created_at: "2024-05-10T12:00:00Z",
    updated_at: "2024-12-08T10:00:00Z",
    created_from_template: "3",
    availableCommandIds: ["autooplata_restart_terminal", "autooplata_equipment_status", "autooplata_login"],
    components: []
  }
];

// Функция для обновления данных в основном сервисе
export function updateEquipmentData() {
  // Обновляем localStorage данными новых резервуаров
  localStorage.setItem('equipment_data', JSON.stringify(newEquipmentData));
  
  // Очищаем кеш, если он есть
  if ((window as any).equipmentCache) {
    delete (window as any).equipmentCache;
  }
  
  console.log('Equipment data updated with new tank configuration');
  return newEquipmentData;
}

export { newEquipmentData };