name: Deploy production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
        PROD_ADDRESS: ${{secrets.PROD_ADDRESS}}
        PROD_USER: ${{secrets.PROD_USER}}
        PROD_PASS: ${{secrets.PROD_PASS}}
        PROD_PORT: ${{secrets.PROD_PORT}}

    steps:
      - name: connect to server and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
            host: ${{env.PROD_ADDRESS}}
            username: ${{env.PROD_USER}}
            password: ${{env.PROD_PASS}}
            port: ${{env.PROD_PORT}}
            script: |
                  cd /var/www/www-root/data/www/prod.dataworker.ru
                  git pull
                  npm ci
                  npm run build
                  pm2 restart tradeframe-prod || pm2 start npm --name "tradeframe-prod" -- run preview
